export const CHAT_KEY = 'chat'

export const MAX_ATTACHMENTS = 2

export enum ModalType {
  NONE = 'NONE',
  IMAGE_DIALOG = 'IMAGE_DIALOG',
  MEDICAL_RECORD_NEW = 'MEDICAL_RECORD_NEW',
  MEDICAL_RECORDS = 'MEDICAL_RECORDS',
}
